#!/bin/sh

BASEDIR=$(realpath $(dirname $0))

sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"

echo "COPYING FILES"
grep '^Cached:' /proc/meminfo
start=$(date +%s%N)
$BASEDIR/../dispatch $BASEDIR/data_src $BASEDIR/data_dest
stop=$(date +%s%N)
diff=$((stop-start))
echo "Took: $diff ns ( $(($diff/1000000)) ms)"
grep '^Cached:' /proc/meminfo

# Cleanup
rm -Rf $BASEDIR/data_dest
mkdir -p $BASEDIR/data_dest
sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"

echo "==============================================="

echo "MOVING FILES"
# Copy files to keep our test folder "untouched"
cp -a $BASEDIR/data_src $BASEDIR/data_move

grep '^Cached:' /proc/meminfo
start=$(date +%s%N)
$BASEDIR/../dispatch -m $BASEDIR/data_move $BASEDIR/data_dest
stop=$(date +%s%N)
diff=$((stop-start))
echo "Took: $diff ns ( $(($diff/1000000)) ms)"
grep '^Cached:' /proc/meminfo

# Cleanup
rm -Rf $BASEDIR/data_dest
mkdir -p $BASEDIR/data_dest
rm -Rf $BASEDIR/data_move/
sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"

echo "==============================================="

echo "CP"

grep '^Cached:' /proc/meminfo
start=$(date +%s%N)
cp -a $BASEDIR/data_src $BASEDIR/data_move
stop=$(date +%s%N)
diff=$((stop-start))
echo "Took: $diff ns ( $(($diff/1000000)) ms)"
grep '^Cached:' /proc/meminfo

# Cleanup
rm -Rf $BASEDIR/data_move
sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"

